# Generated by Django 5.2.6 on 2025-10-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_filme_livro_loja_preco_utilizador_delete_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='andar',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='localidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='morada',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='nif',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='pais',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='porta',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='utilizador',
            name='telefone',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
