# Generated by Django 5.2.6 on 2025-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_utilizador_andar_utilizador_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.CharField(blank=True, default='Livros', max_length=100),
        ),
        migrations.AddField(
            model_name='livro',
            name='imagem_capa',
            field=models.URLField(blank=True, help_text='URL da imagem da capa do livro', null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='novidade',
            field=models.BooleanField(default=False, help_text='Marcar como novidade'),
        ),
    ]
