# Generated by Django 5.2.6 on 2025-11-04 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_filme_options_alter_livro_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Muito mau'), (2, '2 - Mau'), (3, '3 - Médio'), (4, '4 - Bom'), (5, '5 - Excelente')])),
                ('titulo', models.CharField(max_length=200)),
                ('comentario', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False, help_text='Compra verificada')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='members.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_criacao'],
                'unique_together': {('livro', 'utilizador')},
            },
        ),
    ]
