# Generated by Django 5.2.6 on 2025-11-06 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do cupom (ex: VERAO2025)', max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do cupom')),
                ('tipo_desconto', models.CharField(choices=[('percentagem', 'Percentagem'), ('valor_fixo', 'Valor Fixo')], default='percentagem', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do desconto (% ou €)', max_digits=10)),
                ('data_inicio', models.DateTimeField(help_text='Data de início da validade')),
                ('data_fim', models.DateTimeField(help_text='Data de fim da validade')),
                ('ativo', models.BooleanField(default=True, help_text='Cupom ativo')),
                ('uso_maximo', models.IntegerField(default=100, help_text='Número máximo de usos do cupom')),
                ('uso_por_utilizador', models.IntegerField(default=1, help_text='Usos permitidos por utilizador')),
                ('valor_minimo_pedido', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo do pedido para usar o cupom', max_digits=10)),
                ('vezes_usado', models.IntegerField(default=0, help_text='Número de vezes que o cupom foi usado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='UsoCupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uso', models.DateTimeField(auto_now_add=True)),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='members.cupom')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.pedido')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons_usados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Cupom',
                'verbose_name_plural': 'Usos de Cupons',
                'ordering': ['-data_uso'],
            },
        ),
    ]
