# Generated by Django 5.2.6 on 2025-11-06 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_cupom_usocupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='members.cupom'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto_cupom',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do desconto aplicado', max_digits=10),
        ),
    ]
