# Generated by Django 5.2.6 on 2025-11-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_pedido_cupom_pedido_desconto_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateField(blank=True, help_text='Data de publicação do livro', null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='desconto_percentagem',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentagem de desconto (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='livro',
            name='em_oferta',
            field=models.BooleanField(default=False, help_text='Livro em oferta/promoção'),
        ),
        migrations.AddField(
            model_name='livro',
            name='mais_vendido',
            field=models.BooleanField(default=False, help_text='Marcar como mais vendido'),
        ),
        migrations.AddField(
            model_name='livro',
            name='vendas_totais',
            field=models.IntegerField(default=0, help_text='Total de vendas do livro'),
        ),
    ]
