# Generated by Django 5.2.6 on 2026-01-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_livro_data_publicacao_livro_desconto_percentagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='url_netflix',
            field=models.URLField(blank=True, help_text='Link para ver na Netflix', null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='url_prime_video',
            field=models.URLField(blank=True, help_text='Link para ver no Prime Video', null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='URL do trailer (YouTube, Vimeo, etc.)'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['categoria'], name='members_liv_categor_8dc581_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['autor'], name='members_liv_autor_8ec946_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['tem_filme'], name='members_liv_tem_fil_f5ddec_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['-vendas_totais'], name='members_liv_vendas__e1dc79_idx'),
        ),
        migrations.AddIndex(
            model_name='preco',
            index=models.Index(fields=['livro', 'preco'], name='members_pre_livro_i_98dbeb_idx'),
        ),
    ]
